### ISSUE TITLE
Increase the length of the content field of the custom transaction

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain-indexer#261]
https://github.com/CodeChain-io/codechain-indexer/blob/6636c9dfad40a8c72bbdf8dda4a3df2cc37d022c/src/models/custom.ts#L38
Currently, it's 256 bytes string. Please make it unlimited.

**Comment by joojis** [comment]
https://github.com/CodeChain-io/codechain-indexer/pull/262
