### ISSUE TITLE
It takes too long to index some blocks

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-indexer#289]
Indexing some specific block takes more than a minute. I suspect some mint asset but I'm not sure of it.

Slow blocks:
http://corgi.codechain.io/explorer/block/86084
http://corgi.codechain.io/explorer/block/86209

**Comment by Remagpie** [comment]
I think it waits until the timeout if the minted asset's image is unreachable.
https://github.com/CodeChain-io/codechain-indexer/blob/master/src/models/logic/assetimage.ts#L80
