### ISSUE TITLE
Use Postgresql insteand of Elasticsearch

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-indexer#3]

**Comment by xpdlf1004** [comment]
- [ ] Indexing asset UTXO
- [ ] snapshot
- [ ] assetImage
- [ ] log
- [ ] API handler
- [ ] documentation (README)

**Comment by xpdlf1004** [comment]
Add index to the db model

**Comment by xpdlf1004** [comment]
Add an invoice field to the UTXO table

**Comment by xpdlf1004** [comment]
Add the transactions

**Comment by xpdlf1004** [comment]
API handler 
- [ ] status
- [ ] block
- [ ] parcel
- [ ] transaction
- [ ] asset
- [ ] address
- [ ] account

**Comment by sgkim126** [comment]
It's done except the document updates.
I'll close it. The document will be updated in the other pr(#6).
