### ISSUE TITLE
/tx API is not using the index correctly when filtering the result by the asset's type

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain-indexer#313]
To query transactions using an asset type, the Indexer is using the `assetTypeLogs` table that has the `assetType` column. The result rows are ordered by the transactions' `blockNumber` and `transactionIndex`, and the DB should query all `assetTypeLogs` data and sort them.

### Suggestion

Add an index to `assetTypeLogs` table with `assetType`, `blockNumber`, and `transactionIndex` columns.

**Comment by majecty** [comment]
Address로 트랜잭션을 찾을 때도 같은 문제가 있는 것을 발견했습니다. AddressLog에서 Address로 검색한 뒤 Transaction 테이블과 조인해서, blockNumber와 transactionIndex로 소팅하고 있습니다._이렇게하면, sort과정에서 index를 쓰지 않습니다.

There is the same problem when querying Transactions by an address. Indexer selects rows of AddressLog table and sorts them using Transaction table's `blockNumber` column and `transactionIndex` column.

**Comment by majecty** [comment]
The web wallet queries the Transactions table with filtering both `assetType` and `address` data. We may need to create a table that has both `assetType` and `address` field.

**Comment by joojis** [comment]
API usages

* /tx?assetType,page,itemsPerPage (console)
* /tx?page,itemsPerPage,txTypes (explorer)
* /tx?page,itemsPerPage,address (explorer)
* /tx?page,itemsPerPage,assetType (explorer)
* /tx?address,page,itemsPerPage (wallet)
* /tx?address,assetType,page,itemsPerPage (wallet)

**Comment by joojis** [comment]
I'm working on adding an Address-AssetType-Log table.
