### ISSUE TITLE
Yarn run test fails if the instructions are followed

### ISSUE THREAD

**Issue by cubismic** [CodeChain-io/codechain-indexer#54]
FAIL  test/pending-tx.spec.ts
 FAIL  test/db-block-interface.spec.ts
 FAIL  test/mint-transfer.spec.ts
 FAIL  test/snapshot.spec.ts (31.591s)
 FAIL  test/wrap-unwrap.spec.ts (5.398s)
 FAIL  test/store-and-remove.spec.ts (6.713s)
 FAIL  test/log.spec.ts (13.904s)

Test Suites: 7 failed, 4 passed, 11 total
Tests:       21 failed, 19 passed, 40 total
Snapshots:   0 total
Time:        96.003s
Ran all test suites.

Tested in 
Ubuntu 18.04.1 LTS 
nodejs v10.15.1
psql (PostgreSQL) 11.1 (Ubuntu 11.1-3.pgdg18.04+1)
codechain commit 7e689aa86d95f100cc121837cb076b4e77e4957f  ( Feb 7, 2019 )
index commit [e0f5542](https://github.com/CodeChain-io/codechain-indexer/commit/e0f55425cfffa0836ac91b6fbc87ecdc548b6e76) ( Feb 3, 2019 )

for more information, please check the [link](http://kilo.cubist.kr:8529/text/res190207.txt)

**Comment by sgkim126** [comment]
The current indexer is developed on CodeChain b4e05e83b7c8ca21df677ccff26a2d11914b71e3.
Please use this version.

**Comment by cubismic** [comment]
I changed my local CodeChain version to b4e05e83b7c8ca21df677ccff26a2d11914b71e3 and re-tested.
The test fails similarly. 

 FAIL  test/snapshot.spec.ts (33.026s)
 FAIL  test/log.spec.ts (5.187s)
 FAIL  test/store-and-remove.spec.ts (6.443s)
 FAIL  test/wrap-unwrap.spec.ts (5.411s)
 FAIL  test/mint-transfer.spec.ts
 FAIL  test/db-block-interface.spec.ts
 FAIL  test/worker.spec.ts (9.802s)
 FAIL  test/pending-tx.spec.ts

Test Suites: 8 failed, 3 passed, 11 total
Tests:       24 failed, 16 passed, 40 total
Snapshots:   0 total
Time:        80.878s, estimated 91s
Ran all test suites.

Tested in
Ubuntu 18.04.1 LTS
nodejs v10.15.1
psql (PostgreSQL) 11.1 (Ubuntu 11.1-3.pgdg18.04+1)
codechain commit b4e05e83b7c8ca21df677ccff26a2d11914b71e3 ( Jan 23, 2019 )
index commit e0f55425cfffa0836ac91b6fbc87ecdc548b6e76 ( Feb 3, 2019)

**Comment by sgkim126** [comment]
Did you run `NODE_ENV=test yarn run migrate`?

**Comment by cubismic** [comment]
yes I've run `NODE_ENV=test yarn run reset` before test

**Comment by cubismic** [comment]
I've created user and db with pqsl 
But the test still fails

**Comment by sgkim126** [comment]
You should use ` --reseal-min-period 0 --enable-devel-api` to run CodeChain.
See https://github.com/CodeChain-io/codechain-indexer/blob/master/.travis.yml#L13
