### ISSUE TITLE
Add a new endpoint for the chart on the explorer

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-indexer#55]
I need some API to draw the chart on the explorer's main page.

/log/count
params
- filter ( ex  block, tx, assetTransfer, assetMint, setRegularKey ... (tx types))
- date ( ex  2018-09-20)

returns 
- number ( ex 10)

**Comment by joojis** [comment]
I pushed the patch to the master: https://github.com/CodeChain-io/codechain-indexer/commit/893e0296c034aa4d4bb81d0e277463334ebc705c
