### ISSUE TITLE
Fix an error on requesting tx list API

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-indexer#58]
Request
=>  http://localhost:9001/api/tx/count?page=1&itemsPerPage=6&address=tcaqyq4d2d2vf6cxl5nxvtmrj53p2sqlcf3vkasrwh0hx

Response 500 internal server error

server log
```
SequelizeDatabaseError: column transferAsset->orders.owner does not exist 
```

**Comment by xpdlf1004** [comment]
This request returns an error too.

Request => 
http://localhost:9001/api/tx/?page=1&itemsPerPage=6&assetType=0x2e38b1b05dba5c30a2d5421fa5d3a745f63e9efa

Server log
```
column transferAsset->orders.assetType does not exist
```

**Comment by joojis** [comment]
Solved at: https://github.com/CodeChain-io/codechain-indexer/pull/63
