### ISSUE TITLE
Check a transaction invoice before creating UTXO

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-indexer#79]

**Comment by xpdlf1004** [comment]
https://corgi.codechain.io/explorer/tx/7da04db5903ebbe4e72655c8a3cc62e7ce99f75df08da3469f3384f121786dad

Please, check an invoice of the payment transaction too

**Comment by joojis** [comment]
https://github.com/CodeChain-io/codechain-indexer/commit/bb6d46c355272e657dc97e10d85ab3d1b203f018
